{% set name = "ete4" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ete4-{{ version }}.tar.gz
  sha256: 0306ab66c2a1685946f94a4912718a5812dfc3059070300fc25d0e2b881bb8d1

build:
  skip: true  # [py<37 or win]
  entry_points:
    - ete4 = ete4.tools.ete:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=61.0
    - cython
    - pip
  run:
    - python
    - bottle
    - cheroot
    - brotli
    - numpy
    - scipy
    - requests

test:
  imports:
    - ete4
  commands:
    - pip check
    - ete4 --help
  requires:
    - pip

about:
  home: https://etetoolkit.org
  summary: A Python Environment for (phylogenetic) Tree Exploration
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mschilli87
